### ISSUE TITLE
[Bug] OpenShift OAuth Proxy container failed to launch in default namespace

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-helm#133]
### Current Behavior

It seems like the Openshift OAuth proxy image does not specify a numeric non-root user. Thus, `runAsNonRoot: true` cannot be specified on pod.

```
$ podman image inspect quay.io/openshift/origin-oauth-proxy:latest --format '{{.Config.User}}'
0
```

Container failed to launch with status:

```
  - image: quay.io/openshift/origin-oauth-proxy:latest
    imageID: ""
    lastState: {}
    name: cryostat-authproxy
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'container has runAsNonRoot and image will run as root (pod: "cryostat-579d45489-2nt7w_default(337845d4-41c2-4fbb-ab29-3882be6d771a)",
          container: cryostat-authproxy)'
        reason: CreateContainerConfigError
```

### Expected Behavior

Openshift Oauth proxy container should launch successfully.

### Steps To Reproduce

```
helm install cryostat --set authentication.openshift.enabled=true --set core.route.enabled=true ./charts/cryostat/
```

### Environment

```Markdown
CRC version: 2.26.0+233df0
OpenShift version: 4.13.9
```

### Anything else?

Should the chart default to set `runAsUser` for the proxy container?
