### ISSUE TITLE
[Bug] Cryostat does not start when PV is configured

### ISSUE THREAD

**Issue by grzesuav** [cryostatio/cryostat-helm#186]
### Current Behavior

I added pvc with following settings
```yaml

pvc:
  ## @param pvc.enabled Specify whether to use persistentVolumeClaim or EmptyDir storage
  enabled: true
  ## @param pvc.annotations [object] Annotations to add to the persistentVolumeClaim
  annotations: {}
  ## @param pvc.storage Storage size to request for the persistentVolumeClaim
  storage: 5Gi
  ## @param pvc.accessModes Access mode for the persistentVolumeClaim. See: [Access Modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)
  accessModes:
    - ReadWriteOnce
  ## @param pvc.selector [object] Selector for the persistentVolumeClaim. See: [Selector](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)
  selector: {}
  ## @param pvc.storageClassName [string, nullable] The name of the StorageClass for the persistentVolumeClaim. See: [Class](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)
  # storageClassName:
  storageClassName: "managed-csi"

```
 and cryostat does not start, issue is with `cryostat-db` container - 
```
❯ k logs cryostat-dbb678dd9-g7lzd -c cryostat-db
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

in the deployment
```yaml
      volumes:
      - name: cryostat
        persistentVolumeClaim:
          claimName: cryostat
```
and in cryostat-db container
```yaml
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: cryostat
          subPath: postgres
```
I believe some file ownership should be changed ? 

### Expected Behavior

Cryostat start succesfully

### Environment

```Markdown
- OS: 
- Environment: 
- Version:
```
