### ISSUE TITLE
[Task] Allow backport command to cryostatio teams

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-helm#92]
> Yeh exactly! https://docs.mergify.com/commands/restrictions/#command-restriction-format

> Perhaps we want something along these lines instead:
```
commands_restrictions:
  backport:
    conditions:
      - sender=@team
```

_Originally posted by @ebaron in https://github.com/cryostatio/cryostat-helm/issues/90#issuecomment-1756132732_
